name: Build Executable

on:
  push:
    branches: [ "main" ]
    tags:
      - 'v*'
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build on ${{ matrix.artifact_name }}
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        include:
          - os: macos-latest
            artifact_name: midi2osc-macos-arm64
            is_mac: true
          - os: macos-14
            artifact_name: midi2osc-macos-x86_64
            is_mac: true
          - os: ubuntu-latest
            artifact_name: midi2osc-linux
            is_mac: false
          - os: windows-latest
            artifact_name: midi2osc-windows
            is_mac: false

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Poetry
        run: pipx install poetry

      - name: Install project dependencies
        run: poetry install --no-root

      - name: Build executable (macOS)
        if: matrix.is_mac == true
        run: poetry run poe build-mac

      - name: Build executable (Windows / Linux)
        if: matrix.is_mac == false
        run: poetry run poe build

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact_name }}
          path: bin/

  release:
    name: Create GitHub Release
    needs: build
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: artifacts/**/*